# yaml-language-server: $schema=./Schemas/RigConfiguration.json
clockSynchronizer:
  deviceName: TimestampGeneratorGen3
  portName: COM9
cameraController:
  deviceName: CameraControllerGen2
  portName: COM7
  triggers:
    - TriggerName: Trigger0
      triggerFrequency: 50
    - TriggerName: Trigger1
      triggerFrequency: 125
looms:
  - portName: COM8
    bottomPauseTimeSeconds: 1
    dropAcceleration: 18000
    bottomPosition: 3000
    dropMaxVelocity: 10000
    homeVelocity: 200
    id: 00
cameras:
  - cameraName: CameraSide
    triggerName: Trigger0
    exposureTime: 5000
    serialNumber: "23391028"
    gain: 1
    binning: 1
  - cameraName: CameraTop
    triggerName: Trigger0
    exposureTime: 30000
    serialNumber: "23391015"
    gain: 1
    binning: 1
