# yaml-language-server: $schema=./Schemas/RigConfiguration.json
clockSynchronizer:
  deviceName: TimestampGeneratorGen3
  portName: COM9
cameraController:
  deviceName: CameraControllerGen2
  portName: COM7
  triggers:
    - TriggerName: Trigger0
      triggerFrequency: 50
    - TriggerName: Trigger1
      triggerFrequency: 125
looms:
  - portName: COM8
    bottomPauseTimeSeconds: 1
    dropAcceleration: 18000
    bottomPosition: 3000
    dropMaxVelocity: 10000
    homeVelocity: 200
    id: 00
feeders:
  - portName: COM15
    id: 0
    pelletDeliveryRetryCount: 2
    pelletDeliveryTimeoutSeconds: 1
    wheelRadius: -4
  - portName: COM16
    id: 1
    pelletDeliveryRetryCount: 2
    pelletDeliveryTimeoutSeconds: 1
    wheelRadius: -4
cameras:
  - cameraName: CameraSide
    triggerName: Trigger0
    exposureTime: 5000
    serialNumber: "23425448"
    gain: 1
    binning: 1  
  - cameraName: CameraExtra
    triggerName: Trigger0
    exposureTime: 5000
    serialNumber: "23459421"
    gain: 1
    binning: 1
  - cameraName: CameraTop
    triggerName: Trigger0
    exposureTime: 5000
    serialNumber: "23425449"
    gain: 1
    binning: 1
