# yaml-language-server: $schema=./Schemas/RigConfiguration.json
clockSynchronizer:
  deviceName: TimestampGeneratorGen3
  portName: COM9
cameraController:
  deviceName: CameraControllerGen2
  portName: COM7
  triggers:
    - TriggerName: Trigger0
      triggerFrequency: 50
    - TriggerName: Trigger1
      triggerFrequency: 125
cameras:
  - cameraName: CameraSide
    triggerName: Trigger0
    exposureTime: 5000
    serialNumber: "23391028"
    gain: 1
    binning: 1
  - cameraName: CameraTop
    triggerName: Trigger1
    exposureTime: 5000
    serialNumber: "23391015"
    gain: 1
    binning: 1